/** Learner-facing explanations — thptqg-simulation-test-9 (Mock 09) */
export const explanations = {
  1: { explanation: "Trying out local food: thử đồ ăn địa phương; collocation du lịch rất thường gặp.", explanationEvidence: "trying out local food … enhance travel experiences" },
  2: { explanation: "Hỗ trợ thợ thủ công (artisans) và doanh nghiệp địa phương.", explanationEvidence: "Supporting local artisans and businesses" },
  3: { explanation: "Preserve culture: bảo tồn văn hóa (động từ phù hợp với heritage).", explanationEvidence: "helps preserve culture and creates jobs" },
  4: { explanation: "Flavours you can't find in other places: other + danh từ số nhiều (các nơi khác).", explanationEvidence: "can't find in other places" },
  5: { explanation: "Celebrate the culture of the region — culture khớp crafts/traditions.", explanationEvidence: "celebrate the culture of the region" },
  6: { explanation: "While supporting small businesses: while + V-ing — làm giàu trải nghiệm trong khi hỗ trợ kinh tế địa phương.", explanationEvidence: "enriches your travel experience while supporting small businesses" },
  7: { explanation: "Turn the tide ≈ reverse trends / đảo chiều xu thế tiêu cực (ở đoạn quy định cho tình nguyện).", explanationEvidence: "Local authorities aim to turn the tide through regulatory frameworks" },
  8: { explanation: "Beneath the surface… a complex dynamic — paraphrase gần nhất: sau vẻ đẹp là động lực kinh tế–xã hội phức tạp.", explanationEvidence: "beneath the surface … complex dynamic" },
  9: { explanation: "Đoạn 4 (nghề thủ công): số người tham gia, thời lượng workshop, ảnh hưởng thu nhập và truyền nghề.", explanationEvidence: "craft workshops … volunteer programs … simplified teaching" },
  10: { explanation: "Câu về thu nhập truyền thống bị ảnh hưởng chèn sau ví dụ tiểu thương/chợ (II) — nối giữa bằng chứng kinh tế.", explanationEvidence: "insert after market vendor sentence (II)" },
  11: { explanation: "They maintain only 15 positions — they = professional dive operators (chủ ngữ câu trước).", explanationEvidence: "Professional dive operators … they maintain only 15 positions" },
  12: { explanation: "Tóm toàn văn: tình nguyện du lịch tác động đa chiều lên kinh tế truyền thống Koh Rong.", explanationEvidence: "multifaceted impacts on traditional economies" },
  13: { explanation: "Đúng theo bài: khu tình nguyện có bữa ăn trong khu all-inclusive.", explanationEvidence: "volunteers … meals within their compounds" },
  14: { explanation: "NOT mentioned: mức độ hài lòng của khách du lịch (tourist satisfaction) — bài có số liệu khác.", explanationEvidence: "tourist satisfaction not stated" },
  15: { explanation: "Suy luận: chương trình tình nguyện miễn phí lặn/chứng chỉ có thể làm giảm giá trị chuyên môn local.", explanationEvidence: "volunteer programs offer free diving … wages drop" },
  16: { explanation: "Irrevocable damage ≈ thiệt hại lâu dài, khó hoàn tác (gần nghĩa permanent).", explanationEvidence: "irrevocable damage to the traditional economy" },
  17: { explanation: "Diverse trái nghĩa: uniform (đồng nhất, không đa dạng).", explanationEvidence: "diverse landscapes >< uniform" },
  18: { explanation: "Enhance language skills ≈ improve (cải thiện).", explanationEvidence: "enhance their language skills" },
  19: { explanation: "Lợi ích cho tình nguyện viên (hiểu văn hóa, trải nghiệm) nêu ở đoạn mở.", explanationEvidence: "Paragraph 1: deeper understanding … positive impact" },
  20: { explanation: "Phần về y tế: tìm đoạn nói clinics, health campaigns — theo đánh số đoạn trong đề.", explanationEvidence: "healthcare … clinics and public health campaigns" },
  21: { explanation: "Đúng: tình nguyện viên y khoa có thể tham gia chiến dịch y tế cộng đồng.", explanationEvidence: "assist in public health campaigns" },
  22: { explanation: "NOT mentioned: xây hạ tầng đô thị như trọng tâm tình nguyện — bài nhấn giáo dục, y tế, môi trường.", explanationEvidence: "urban infrastructure not a volunteer focus area" },
  23: { explanation: "They play a crucial role — they = volunteers (ở đoạn môi trường).", explanationEvidence: "By participating in these programs, they play a crucial role" },
  24: { explanation: "Paraphrase: hỗ trợ lớp học & hoạt động ngoại khóa giúp thu hẹp khoảng cách giáo dục.", explanationEvidence: "assisting in classrooms or extracurricular activities … bridge gaps" },
  25: { explanation: "Equipped with a fast processor: equipped with + danh từ (trang bị).", explanationEvidence: "laptop is equipped with a fast processor" },
  26: { explanation: "Allowing you to complete assignments: allow + O + to V.", explanationEvidence: "allowing you to complete assignments … without delays" },
  27: { explanation: "Long hours of typing: trật tự danh từ chuẩn cho bàn phím công thái học.", explanationEvidence: "keyboard designed for long hours of typing" },
  28: { explanation: "Preloaded with apps: quá khứ phân từ (cài sẵn ứng dụng).", explanationEvidence: "Preloaded with useful apps" },
  29: { explanation: "Excel academically: trạng từ academically bổ nghĩa cho động từ excel.", explanationEvidence: "excel academically" },
  30: { explanation: "Peace of mind: thành ngữ ‘yên tâm’.", explanationEvidence: "giving you peace of mind" },
  31: { explanation: "Trình tự d-b-e-a-c: công nghệ đổi cách sống (d) → thông tin dễ tiếp cận (b) → ví dụ smartphone/y tế (e) → smarthome thêm (a) → cân bằng đổi mới và kết nối con người (c).", explanationEvidence: "technology expository d-b-e-a-c" },
  32: { explanation: "Chatbot: Nhat mở ý → An hỏi → An bổ sung (b-c-a).", explanationEvidence: "b-c-a chatbot discussion" },
  33: { explanation: "Email Sarah: cảm ơn gợi ý nhà hàng → khen món → cảm ơn → hỏi thăm → hẹn gặp (a-b-c-d-e).", explanationEvidence: "thank-you email flow" },
  34: { explanation: "Chọn ngành: Mike hỏi (b) → Jack chưa chắc (d) → nói engineering (c) → Mike khen (a).", explanationEvidence: "b-d-c-a study choice" },
  35: { explanation: "AI trong media: b mở tranh luận → c nội dung nhanh → a chính xác/sáng tạo → e lai ghép → d tương lai.", explanationEvidence: "b-c-a-e-d" },
  36: { explanation: "Urbanization: mệnh đề quan hệ mô tả xu thế di cư nông thôn–thành thị (chọn câu đầy đủ ngữ pháp trong đề).", explanationEvidence: "urbanization involves migration to cities" },
  37: { explanation: "Áp lực hạ tầng không theo kịp dòng người nhập cư — ý nối sau ‘strain on infrastructure’.", explanationEvidence: "demand for housing, transportation … exceeds supply" },
  38: { explanation: "Bất bình đẳng: người nghèo vào khu ổ chuột, thiếu dịch vụ — chọn câu tổng hợp hệ quả xã hội (D).", explanationEvidence: "social inequalities … informal settlements" },
  39: { explanation: "Quy hoạch đô thị: ưu tiên hạ tầng bền vững, nhà giá rẻ, tiếp cận công bằng tài nguyên.", explanationEvidence: "urban planning … sustainable infrastructure and affordable housing" },
  40: { explanation: "Addressing these challenges head-on — V-ing mở câu, chủ ngữ chính sau đó là governments…", explanationEvidence: "Addressing these challenges head-on, governments can …" },
};
