/** Learner-facing explanations — thptqg-simulation-test-8 (Mock 08) */
export const explanations = {
  1: { explanation: "Mô tả biểu đồ: mở d (giới thiệu biểu đồ ba thành phố) → e (xu hướng chung) → b (Atlanta) → c (Charlotte) → a (New Orleans).", explanationEvidence: "chart description d-e-b-c-a" },
  2: { explanation: "Thư thông báo trúng giải: b chúc mừng → a khen menu → d phần thưởng lớp học → c liên hệ chi tiết.", explanationEvidence: "prize letter b-a-d-c" },
  3: { explanation: "Thảo luận bảo vệ hệ sinh thái: d mở ý → a gợi ý tiết kiệm năng lượng → e xe điện → c trồng cây → b ghi chép đề xuất.", explanationEvidence: "ecosystem dialogue d-a-e-c-b" },
  4: { explanation: "Robot hướng dẫn: b giới thiệu → a khách chào → c chụp ảnh.", explanationEvidence: "b-a-c robot guide" },
  5: { explanation: "Nhà thông minh 2035: c mở tương lai → b hệ thống điều khiển → d khi vắng nhà → a trẻ/vật nuôi → e tóm lợi ích.", explanationEvidence: "smart home c-b-d-a-e" },
  6: { explanation: "Make up ≈ chiếm (thời gian): Working makes up around one-third of life.", explanationEvidence: "Working makes up around one-third … of life" },
  7: { explanation: "Spend your working time: spend + time (dùng thời gian làm việc thế nào).", explanationEvidence: "how you'd like to spend your working time" },
  8: { explanation: "A number of tests: cụm đếm số lượng bài kiểm tra.", explanationEvidence: "There are a number of tests you can take" },
  9: { explanation: "Each sector and its goals: mục tiêu/ngành nghề của từng lĩnh vực.", explanationEvidence: "each sector and its respective goals" },
  10: { explanation: "In addition to thinking on your own: ngoài việc tự suy nghĩ, còn có thể nhờ tài nguyên.", explanationEvidence: "In addition to … on your own, you can also turn to … resources" },
  11: { explanation: "Other career resources: other + danh từ số nhiều (các nguồn khác).", explanationEvidence: "turn to other career resources" },
  12: { explanation: "Câu gạch chân: lạm dụng AI ngày càng dễ tiếp cận → lo ngại đạo đức và an toàn.", explanationEvidence: "AI abuse is a growing concern … ethical and safety issues" },
  13: { explanation: "Câu ‘mimic human behaviour’ nối tiếp ngay sau (II): vừa nói bot giả làm người thật, rồi giải thích vì sao hiệu quả trước khi sang (III) về đổi ý kiến — đáp án (II) = index 3 trong đề.", explanationEvidence: "after (II): bots imitate real users, then clarify mimicry" },
  14: { explanation: "They can change opinions — they = bots (AI-driven bots).", explanationEvidence: "These bots … they can change opinions" },
  15: { explanation: "Sparked a debate ≈ started a discussion on (mở ra cuộc tranh luận).", explanationEvidence: "sparked a debate about ethical use" },
  16: { explanation: "EXCEPT: bài không nêu ‘thu hút sự chú ý đến ứng dụng AI’ như một mục đích dùng nhận diện khuôn mặt; các ý kia có trong đoạn.", explanationEvidence: "NOT mentioned: gaining attention toward AI application" },
  17: { explanation: "Đoạn 3 trọng tâm riêng tư: nhận diện khuôn mặt dùng trái phép, bán dữ liệu quảng cáo.", explanationEvidence: "paragraph 3 privacy invasion" },
  18: { explanation: "Empower (trao quyền) trái nghĩa: restrict (hạn chế).", explanationEvidence: "empower >< restrict" },
  19: { explanation: "NOT true: nhận diện khuôn mặt không chỉ dùng cho cơ quan chức năng — bài nêu cả tổ chức tư.", explanationEvidence: "private organisations use it without consent" },
  20: { explanation: "Suy luận cân bằng: không phải mọi ứng dụng AI đều xấu, nhưng lạm dụng gây hậu quả nghiêm trọng.", explanationEvidence: "balanced inference on AI misuse" },
  21: { explanation: "Tóm cả bài: nhiều dạng lạm dụng AI + giải pháp luật và giáo dục.", explanationEvidence: "AI abuse … regulations and awareness" },
  22: { explanation: "Immerse yourself in local culture: giới từ in với immerse.", explanationEvidence: "immersing yourself in local culture" },
  23: { explanation: "A service connecting travelers: connecting — mệnh đề rút gọn/service đồng hành.", explanationEvidence: "a service connecting travelers with locals" },
  24: { explanation: "Authentic cultural experiences: trật tự tính từ + danh từ (trải nghiệm văn hóa chân thực).", explanationEvidence: "provide you with authentic cultural experiences" },
  25: { explanation: "Without worrying about transportation: lo ngại di chuyển/ phương tiện.", explanationEvidence: "without worrying about transportation" },
  26: { explanation: "Make lifelong friends: collocation cố định.", explanationEvidence: "make lifelong friends" },
  27: { explanation: "Sign up today to experience the world: to experience — mục đích sau động từ.", explanationEvidence: "Sign up today to experience the world" },
  28: { explanation: "Bài không đề cập nghiên cứu hành vi động vật trước phun trào.", explanationEvidence: "NOT: studying animal behavior before eruption" },
  29: { explanation: "Evacuate (sơ tán) trái nghĩa: remain (ở lại).", explanationEvidence: "evacuate >< remain" },
  30: { explanation: "They can also use that information — they = scientists (theo đoạn giám sát núi lửa).", explanationEvidence: "Scientists … They can also use that information" },
  31: { explanation: "almost as soon as it happens ≈ phát hiện và phân tích gần như thời gian thực.", explanationEvidence: "tell what is happening … almost as soon as it happens" },
  32: { explanation: "Comprehensive analysis ≈ phân tích chi tiết, toàn diện.", explanationEvidence: "A comprehensive analysis of these factors" },
  33: { explanation: "Đúng theo bài: nếu dự báo phun trào, chính phủ chuẩn bị lương thực, nước.", explanationEvidence: "Governments can prepare emergency supplies" },
  34: { explanation: "Theo dõi khí, nhiệt, nước quanh núi lửa — nội dung chính ở đoạn có monitoring chi tiết (đoạn 5 trong bản in).", explanationEvidence: "monitor gases, temperature, and water" },
  35: { explanation: "If a volcanic eruption is predicted… — mối quan hệ điều kiện ở đoạn 2.", explanationEvidence: "conditional: If … predicted, people can evacuate" },
  36: { explanation: "Great art có thể thay đổi dần theo thời gian vì dư luận và xu hướng nghệ thuật thay đổi (B: gradually change … shifting public opinions).", explanationEvidence: "ideas about what great art is change over time" },
  37: { explanation: "When it was displayed at the Ferus Gallery — mệnh đề thời gian + bị động phù hợp.", explanationEvidence: "Warhol … when displayed … Ferus Gallery" },
  38: { explanation: "Equivalent VIII: lắp gạch trông như ‘chỉ là đống gạch’ — mô tả khớp đáp A.", explanationEvidence: "bricks on the floor … ordinary pile of bricks" },
  39: { explanation: "The Tate, a famous gallery in London — mệnh đề danh từ đồng vị.", explanationEvidence: "The Tate, a famous gallery in London" },
  40: { explanation: "Câu hỏi song song: genius hay … ý kiến kém thiện cảm hơn — điền mệnh đề tương xứng ngữ pháp.", explanationEvidence: "parallel: works of genius, or … less favorable" },
};
