/** Learner-facing explanations for thptqg-simulation-test-3 (Mock 03) */
export const explanations = {
  1: { explanation: "Động từ cố định với sự kiện là take place (diễn ra); các cụm kia không đi với ngày giờ địa điểm theo cách này.", explanationEvidence: "Contest will take place on December 15." },
  2: { explanation: "Showcase nghĩa là phô diễn, giới thiệu kỹ năng trước công chúng; phù hợp ngữ cảnh hội thi hùng biện.", explanationEvidence: "showcase their skills in argumentation." },
  3: { explanation: "Including + danh từ liệt kê phần thưởng đi kèm; which includes cần mệnh đề, include sai dạng từ.", explanationEvidence: "prizes including trophies and certificates." },
  4: { explanation: "This event chỉ sự kiện đơn (cuộc thi) vừa nhắc; these/others không khớp số và chỉ định.", explanationEvidence: "this event promises lively discussions." },
  5: { explanation: "Sau enjoy trong văn phong này thường dùng V-ing: enjoy watching the atmosphere.", explanationEvidence: "enjoy watching … the exciting atmosphere." },
  6: { explanation: "Be ready for + danh từ: sẵn sàng cho một đêm…; ready of/out không đi kèm cấu trúc chuẩn ở đây.", explanationEvidence: "be ready for a night of powerful debates." },
  7: { explanation: "Set a new standard là cụm quen dùng cho sản phẩm công nghệ; setting… standard bổ nghĩa cho iPhone 16.", explanationEvidence: "setting a new standard in smartphone innovation." },
  8: { explanation: "Mệnh đề kết quả: thiết bị tốt nên (so) bạn có trải nghiệm đẳng cấp; although/despite cần mâu thuẫn.", explanationEvidence: "performance … so you can enjoy … experience." },
  9: { explanation: "Trật tự tính từ + danh từ: incredibly (trạng từ) bổ nghĩa cho vibrant colors.", explanationEvidence: "incredibly vibrant colors … resolution." },
  10: { explanation: "Stay connected với mạng và thiết bị; go/do/make không collocation với connected trong quảng cáo pin.", explanationEvidence: "All-Day Battery Life: stay connected longer." },
  11: { explanation: "Sustainable materials: vật liệu bền vững; các dạng từ khác sai chức năng từ loại.", explanationEvidence: "Built with sustainable materials … carbon footprint." },
  12: { explanation: "In the palm of your hand: thành ngữ quen trong quảng cáo điện thoại.", explanationEvidence: "experience the future in the palm of your hand." },
  13: { explanation: "Trình tự hội thoại: Mark hỏi Giáng sinh → Binh nói gần đến Giáng sinh → Binh kể đang chờ gia đình và đồ ăn/phim.", explanationEvidence: "b → c → a: mở chủ đề → hỏi đáp → chi tiết." },
  14: { explanation: "Mở bằng e (tin cấm điện thoại) → b (Jane đồng ý) → a (Lan phản biện) → c (Jane đề xuất cân bằng) → d (Lan chốt).", explanationEvidence: "e-b-a-c-d: lời mở → ý kiến → phản hồi → giải pháp." },
  15: { explanation: "Đoạn mở d-a: nêu nhược điểm AI → ví dụ mất việc; tiếp theo c-bias, e-privacy, b-quy định chậm.", explanationEvidence: "d-a-c-e-b: tổng quan → chi tiết → mở rộng → kết." },
  16: { explanation: "Thư thất lạc đồ: e mở ý → a chi tiết chuyến → d nhờ tìm → c sẵn sàng bổ sung → b cảm ơn.", explanationEvidence: "e-a-d-c-b: mục đích → sự việc → yêu cầu → điều kiện → kết." },
  17: { explanation: "Bài về Tokyo 2024: e chủ đề → c smart city → b hạ tầng xanh → d kiến trúc xanh → a kết sự kiện và di sản.", explanationEvidence: "e-c-b-d-a: dẫn nhập → phát triển → minh họa → mở rộng → kết luận." },
  18: { explanation: "Cụm hiện tại phân từ bổ nghĩa hands-on training, song song cấu trúc câu với chủ ngữ schools.", explanationEvidence: "focus on hands-on training … ensuring … experience." },
  19: { explanation: "Câu hoàn chỉnh độc lập nêu lợi thế chi phí; that-clause ở C thiếu động từ chính đầy đủ.", explanationEvidence: "more affordable than four-year degrees … avoid debt." },
  20: { explanation: "Many industries need workers, so (kết quả) giáo dục nghề là lựa chọn tốt; nối hợp lý nhất với đoạn trước.", explanationEvidence: "need skilled workers, so vocational education …" },
  21: { explanation: "ATA College là chủ ngữ số ít, cần động từ exemplifies (minh họa); các lựa chọn chia thì/tận cùng không khớp.", explanationEvidence: "ATA College … exemplifies the opportunities …" },
  22: { explanation: "Câu kết mở bằng For those seeking… trực tiếp, tích cực; các lựa chọn có rough/challenging sai sắc thái.", explanationEvidence: "For those seeking a direct route to success …" },
  23: { explanation: "They đứng ngay sau chủ đề AI-powered robots (learn from previous surgeries).", explanationEvidence: "While AI-powered robots can process … and learn … they …" },
  24: { explanation: "Address the shortage ≈ giải quyết/đáp ứng tình trạng thiếu bác sĩ; không phải encourage hay ignore.", explanationEvidence: "help address the shortage of experienced surgeons." },
  25: { explanation: "Flawed = có khuyết điểm; trái nghĩa gần nhất là perfect trong bốn lựa chọn.", explanationEvidence: "If the data … is flawed → opposite: perfect data." },
  26: { explanation: "Bài không nói khó lập trình phẫu thuật phức tạp; các ý empathy, pháp lý, chi phí đều có.", explanationEvidence: "Paragraph 3 lists empathy, legal issues, costs, data, cybersecurity." },
  27: { explanation: "Đoạn 2 nêu chi phí đầu tư cao nhưng lợi ích dài hạn có thể giảm chi phí y tế.", explanationEvidence: "costly … long-term benefits … reduced healthcare costs." },
  28: { explanation: "Cân bằng lợi ích AI với thách thức đạo đức và cảm xúc = striking a balance … key role.", explanationEvidence: "Balancing the benefits of AI with the ethical and emotional complexities." },
  29: { explanation: "Thiếu bác sĩ và cải thiện y tế nằm ở đoạn 2 (benefits of AI systems).", explanationEvidence: "Paragraph 2: address shortage … improve healthcare availability." },
  30: { explanation: "Hợp tác AI–bác sĩ nằm ở đoạn cuối (complement, collaborative approach).", explanationEvidence: "Paragraph 4: complement rather than replace … collaborative approach." },
  31: { explanation: "Paraphrase đúng: chuyển hướng du lịch xanh, trách nhiệm với thiên nhiên và cộng đồng; B giữ đủ nghĩa.", explanationEvidence: "shifting towards green tourism … sustainability … responsibility." },
  32: { explanation: "Conscious of impact ≈ aware of impact trong ngữ cảnh du lịch bền vững.", explanationEvidence: "tourists are increasingly conscious of their environmental impact." },
  33: { explanation: "Đoạn 2: người du lịch sẵn sàng đổi thói quen, giảm rác, ủng hộ địa phương theo khảo sát.", explanationEvidence: "82% EU … 76% Vietnam international tourists … willing to …" },
  34: { explanation: "Them trỏ về domestic tourists (chủ ngữ của mệnh đề trước: 88% of them).", explanationEvidence: "domestic tourists … 88% of them embracing green tourism practices." },
  35: { explanation: "Câu về Cô Tô là ví dụ song song với Hội An/Phong Nha; chèn sau (II) hoặc trong chuỗi ví dụ (III).", explanationEvidence: "Insert after examples of destinations pioneering green initiatives." },
  36: { explanation: "Đoạn 4 nêu National Action Plan, chiến lược du lịch—chính phủ hỗ trợ chủ động.", explanationEvidence: "Vietnam's government supports this shift … National Action Plan." },
  37: { explanation: "Bài không dùng sự sụt giảm khách quốc tế do hạn chế đi lại là nhân tố thúc đẩy du lịch xanh.", explanationEvidence: "Growth drivers: awareness, eco options, domestic behavior—not D." },
  38: { explanation: "Immersive = sâu, đắm chìm; trái nghĩa gần superficial (hời hợt).", explanationEvidence: "immersive experiences ↔ superficial experiences." },
  39: { explanation: "Suy luận: xu hướnh quan tâm thực hành bền vững để bảo vệ môi trường khớp toàn bài.", explanationEvidence: "Tourists … ready to reduce waste … eco-friendly options." },
  40: { explanation: "Tóm tắt đầy đủ nhất: tăng trưởng du lịch + chính phủ ưu tiên xanh + cộng đồng + môi trường.", explanationEvidence: "Government prioritizing green tourism … sustainability … communities." },
};
