export const explanations = {
  1: { explanation: "a service designed to connect…: quá khứ phân từ bổ nghĩa cho service, bị động rút gọn.", explanationEvidence: "a service designed to connect travelers with locals." },
  2: { explanation: "Show you around: dẫn đi tham quan; collocation quen với greeter.", explanationEvidence: "locals eager to show you around." },
  3: { explanation: "Interested in: cấu trúc tính từ + in + danh động từ/tour.", explanationEvidence: "whether you're interested in a guided tour." },
  4: { explanation: "Dropped off: đưa xuống xe tại điểm; drop off tại địa điểm.", explanationEvidence: "being dropped off at a spot of interest." },
  5: { explanation: "Wanting to meet locals: sau wanting + to V; nghĩa muốn gặp gỡ người địa phương.", explanationEvidence: "solo travelers wanting to meet locals." },
  6: { explanation: "Authentic local culture: thứ tự tính từ + local + danh từ (culture).", explanationEvidence: "experience authentic local culture." },
  7: { explanation: "A large selection of projects: selection of = tập hợp các đồ án được nộp.", explanationEvidence: "received a large selection of projects from students." },
  8: { explanation: "In addition to a scholarship: bổ sung thêm học bổng ngoài phần thưởng khác.", explanationEvidence: "In addition to a scholarship … gift card." },
  9: { explanation: "Will be showcased / showcase at Expo: trưng bày dự án tại hội chợ.", explanationEvidence: "her project will be showcased at the Annual Science Expo." },
  10: { explanation: "Outstanding projects: dự án xuất sắc; phù hợp lời khen từ ban giám khảo.", explanationEvidence: "we received many outstanding projects." },
  11: { explanation: "Each student: mỗi học sinh (đơn) được nhận phần thưởng ghi nhận.", explanationEvidence: "Each student who entered will receive … recognition." },
  12: { explanation: "Mementos of recognition: vật kỷ niệm/ biểu trưng ghi nhận nỗ lực (formal register).", explanationEvidence: "an award of recognition for their effort." },
  13: { explanation: "b-a-d-c-e: mở đề tài ngôn ngữ mạng → ví dụ nghiên cứu → dữ liệu 65% → mở rộng → kết luận ứng xử.", explanationEvidence: "Logical expository flow from topic to conclusion." },
  14: { explanation: "c-e-b-a-d: mở lời khen tổng thể → phản hồi tán thưởng → chi tiết đồ ăn/nhạc → đồng ý thêm.", explanationEvidence: "Wedding reception dialogue: reaction chain." },
  15: { explanation: "a-b-d-c-e: mở tổng hại sức khỏe → bằng chứng bệnh → men răng → caffeine → kết luận.", explanationEvidence: "Cause–effect paragraph on soft drinks." },
  16: { explanation: "a-b-c: Tom nói học tập → Anna hỏi môn → Tom trả lời chi tiết.", explanationEvidence: "Study focus three-turn conversation." },
  17: { explanation: "a-b-c-e-d: mở lời mời album → mong muốn thảo luận → hẹn listening session → nhắn lịch.", explanationEvidence: "Email/letter inviting friend to listen together." },
  18: { explanation: "Opera was first developed in Florence: câu đầy đủ chủ vị, thì quá khứ đơn.", explanationEvidence: "The art form … was first developed … during the 1590s." },
  19: { explanation: "Which they found rigid…: đại từ quan hệ thay Church music (alternative composers sought).", explanationEvidence: "alternative to … music for the Church, which they found rigid…" },
  20: { explanation: "Opera was an almost immediate success: thành công ngay tại Italy; các lựa chọn kia sai ngữ pháp.", explanationEvidence: "Opera was an almost immediate success in Italy." },
  21: { explanation: "Since it was a new art form: nhân–quả với câu sau everything was new.", explanationEvidence: "Since … new art form, everything was new and untested." },
  22: { explanation: "The format … was approaching what we know today: quá khứ, đang tiến tới định dạng hiện đại.", explanationEvidence: "By the early 1600s … format … approaching … today." },
  23: { explanation: "Paraphrase: túi nilon thường kết thúc ở đường nước, bãi biển… = end up in.", explanationEvidence: "Once they become litter … find their way into … waterways, parks…" },
  24: { explanation: "Outcomes ≈ consequences (hậu quả); không phải benefits hay contamination trực tiếp.", explanationEvidence: "unaware of the outcomes … will take place in the future." },
  25: { explanation: "Them trỏ về plastic bags (chủ ngữ số nhiều ngay trước: they are responsible).", explanationEvidence: "they are responsible for causing pollution … most of us unaware of the outcomes …" },
  26: { explanation: "Worsened opposite improved; các lựa chọn declined/weakened/reduced gần nghĩa worsen.", explanationEvidence: "worsened >< improved." },
  27: { explanation: "Đoạn 2 nói chính phủ thỉnh thoảng ra lệnh cấm túi nilon—tức là có lệnh cấm, không phải 'không cấm'.", explanationEvidence: "government passes out an order banning store owners from providing plastic bags." },
  28: { explanation: "Ý A là hệ quả phụ (400 năm phân hủy) được nêu như nhận xét, không phải 'tác hại môi trường' theo dạng động vật/ô nhiễm như các ý khác.", explanationEvidence: "No one will live … to witness decomposition—stated as comment, not listed harm like wildlife death." },
  29: { explanation: "Vấn đề lớn nhất: không phân hủy sinh học và ô nhiễm biển được nhấn mạnh ở đoạn 3.", explanationEvidence: "Paragraph 3: non-biodegradable, major sea pollutants, wildlife deaths." },
  30: { explanation: "Tote bag thay thế túi nilon nêu ở đoạn 4 (cuối bài).", explanationEvidence: "Paragraph 4: A tote bag can make a good substitute…" },
  31: { explanation: "Câu về chuyên gia xem xét lại đầu tư sau thống kê tiêu cực—chèn sau (III) khi đã có số liệu sốc.", explanationEvidence: "After (III) shock statistics → experts reconsider." },
  32: { explanation: "Russian roulette = chấp nhận rủi ro cực lớn khi băng qua hành lang.", explanationEvidence: "animals … Russian roulette … life threatening risks." },
  33: { explanation: "Their = conservationists (unintended consequences of their interventions).", explanationEvidence: "conservationists … concerned about … their … interventions." },
  34: { explanation: "Không nêu mất cân bằng hệ sinh thái (ecosystem balance); có hành vi động vật, kinh tế địa phương, săn trộm.", explanationEvidence: "NOT mentioned: disruption of ecosystem balance." },
  35: { explanation: "Đoạn 4: bồi thường trên giấy tờ nhưng không đủ hỗ trợ tài chính cho cộng đồng.", explanationEvidence: "compensation schemes … rarely translate into adequate financial support." },
  36: { explanation: "Gạch chân: gắn lối đi động vật vào hạ tầng hiện có thay vì chỉ hành lang nhân tạo tách biệt.", explanationEvidence: "integrating wildlife passages into existing human infrastructure." },
  37: { explanation: "Malaysia elevated highways + underpasses → lợi ích đa bên (win-win) như bài nêu.", explanationEvidence: "elevated highways incorporate natural underpasses … win-win." },
  38: { explanation: "Unabated = không giảm; opposite weakened.", explanationEvidence: "urban sprawl continues unabated ↔ weakened." },
  39: { explanation: "Hành lang dự đoán trước giúp săn trộng—suy ra lối đi bảo vệ có thể làm tăng rủi ro săn trộng theo thời gian.", explanationEvidence: "poachers … caught wind of these predictable migration routes." },
  40: { explanation: "B tóm tắt dự án Mekong, hạn chế hành lang truyền thống và hướng chiến lược mới.", explanationEvidence: "Greater Mekong Project … limitations … new strategies." },
};
