/** Learner-facing explanations — thptqg-simulation-test-5 (Mock 05) */
export const explanations = {
  1: { explanation: "Cấu trúc make + O + tính từ: trí tuệ cảm xúc là phẩm chất khiến con người trở nên intelligent (thông minh/ có hiểu biết xã hội).", explanationEvidence: "emotional intelligence … makes humans intelligent" },
  2: { explanation: "Trật tự tính từ: human + social + skill (kỹ năng xã hội mang tính con người).", explanationEvidence: "a unique human social skill" },
  3: { explanation: "Sau instead of dùng V-ing: instead of getting upset (thay vì nổi nóng).", explanationEvidence: "Instead of getting upset when problems arise" },
  4: { explanation: "Mệnh đề quan hệ chỉ người: People who develop emotional intelligence…", explanationEvidence: "People who develop emotional intelligence usually communicate better" },
  5: { explanation: "Collocation cố định: respect for the feelings of others (tôn trọng cảm xúc người khác).", explanationEvidence: "have respect for the feelings of others" },
  6: { explanation: "Connect with others: kết nối với người khác; phù hợp ngữ cảnh ý nghĩa sâu sắc trên mạng.", explanationEvidence: "helps us connect with others in meaningful ways" },
  7: { explanation: "Trong thông báo hàng không, ‘trạm thời tiết / điều kiện thời tiết bất ngờ’ thường diễn đạt bằng collocation với weather; chọn phương án khớp ngữ cảnh delay.", explanationEvidence: "due to unforeseen weather … flight has been delayed" },
  8: { explanation: "Departure time: giờ cất cánh dự kiến mới (sau khi hoãn).", explanationEvidence: "The new estimated departure time … 2:15 PM" },
  9: { explanation: "Whereas có thể dùng để đối chiếu tình huống (xét trong lúc chờ); đọc kỹ đoạn để thấy mạch lời xin lỗi và gợi ý chờ.", explanationEvidence: "Whereas … we encourage you to relax in the departure lounge" },
  10: { explanation: "Complementary refreshments: đồ ăn nhẹ/đồ uống đi kèm bổ sung trải nghiệm (kèm Wi-Fi); đừng nhầm với complimentary (miễn phí) nếu đề hỏi collocation khác.", explanationEvidence: "complimentary vs complementary — context: lounge services" },
  11: { explanation: "Connecting flights: chuyến nối; linking cũng chỉ nối chuyến trong một số bài.", explanationEvidence: "questions regarding your travel itinerary or connecting flights" },
  12: { explanation: "Sau delay, hãng thường ‘trấn an’ hành khách: reassure your safety (đảm bảo an toàn). Nếu đáp trong máy khác, ưu tiên assure/reassure theo nghĩa trấn an.", explanationEvidence: "work to reassure / assure your safety" },
  13: { explanation: "Trình tự: mở đề (đi bảo tàng) → phản hồi → kể trải nghiệm VR.", explanationEvidence: "b → a → c: topic → reaction → detail" },
  14: { explanation: "Gợi ý đi bộ núi: mở lời mời (d) → đồng ý (e) → chi tiết (a,b,c).", explanationEvidence: "d-e-a-b-c: invitation → acceptance → planning" },
  15: { explanation: "Email đổi lịch họp: thông báo không tham dự (c) → lý do (d) → đề xuất thứ Sáu (a) → nhận lỗi (b) → hy vọng được sắp xếp (e).", explanationEvidence: "c-d-a-b-e flow" },
  16: { explanation: "Bài học suốt đời: mở e (lợi ích nghề nghiệp) → d (ví dụ sự nghiệp) → b (kỹ năng cạnh tranh) → a (phát triển cá nhân) → c (sở thích).", explanationEvidence: "e-d-b-a-c" },
  17: { explanation: "Bài AI: c mở nhược điểm → b mất việc → d tin giả → e video giả → a giải pháp.", explanationEvidence: "c-b-d-e-a" },
  18: { explanation: "There are chatbots used… / chatbots used…: quá khứ phân từ bổ nghĩa danh từ.", explanationEvidence: "a wide variety of chatbots used artificial intelligence nowadays" },
  19: { explanation: "Cấu trúc song song, nhấn mạnh dashboard: how its user-friendly dashboard is (hoặc cách diễn đạt tương đương trong đề).", explanationEvidence: "Perhaps the best feature … how its user-friendly dashboard is" },
  20: { explanation: "Chủ ngữ AI + động từ chia số ít: It provides quick responses…", explanationEvidence: "chatbot52's AI … provides quick responses" },
  21: { explanation: "Cần câu đầy đủ chủ-vị: there are some questions that … cannot answer.", explanationEvidence: "This means that there are some questions that … cannot provide answers" },
  22: { explanation: "Một số người dùng báo lỗi khi hỏi câu phức tạp — câu mở đầu rõ ràng (Some users reported…).", explanationEvidence: "Some users reported issues when asking it more complex questions" },
  23: { explanation: "Bài không nói Keller đoạt Nobel; Nobel thuộc Einstein. NOT mentioned = giải Nobel của Helen.", explanationEvidence: "Helen Keller … Nobel Prize not stated" },
  24: { explanation: "Lifelong (trọn đời) trái nghĩa gần nhất: temporary (tạm thời).", explanationEvidence: "lifelong >< temporary" },
  25: { explanation: "Their trỏ về ‘cả hai’ nhân vật và thành tựu học tập suốt đời của họ.", explanationEvidence: "both … remained lifelong learners … their hard work" },
  26: { explanation: "Groundbreaking ≈ revolutionary (đột phá, mở lối mới).", explanationEvidence: "groundbreaking work … theory of relativity" },
  27: { explanation: "Câu gạch chân: họ chứng minh giá trị của học suốt đời — paraphrase gần nhất: achievements highlight how essential lifelong learning is.", explanationEvidence: "proof of the importance and value of lifelong learning" },
  28: { explanation: "Đúng theo bài: Keller học Braille nhờ Anne Sullivan.", explanationEvidence: "Keller learned to read and write using Braille" },
  29: { explanation: "Thành tích đại học của Keller nằm ở đoạn 2 (Radcliffe College).", explanationEvidence: "Paragraph 2: graduated from Radcliffe College" },
  30: { explanation: "Học suốt đời của cả hai được nhấn ở đoạn cuối (sau khi đã kể Nobel và sách của Keller).", explanationEvidence: "Paragraph discussing lifelong dedication — last body paragraph" },
  31: { explanation: "Câu về phơi sáng lâu chèn sau gợi ý selfie chỉ một tấm (Cornelius) — vị trí III/IV tùy mạch; chọn theo sát bài in.", explanationEvidence: "Cornelius … one photo — insert near II-III transition" },
  32: { explanation: "Mainstream khi điện thoại phổ biến ≈ widespread (phổ biến rộng).", explanationEvidence: "when smartphones became mainstream" },
  33: { explanation: "They trong câu Britney/Paris — chỉ hai người đó (khi nói họ nhầm về việc ‘phát minh’ selfie).", explanationEvidence: "they declared on Twitter … they had invented" },
  34: { explanation: "Bài không nêu selfie của Giáo hoàng như ví dụ ‘trong quá khứ’ theo dạng câu hỏi NOT.", explanationEvidence: "NOT mentioned as historical selfie example — Pope" },
  35: { explanation: "Đoạn 3 giải thích nguồn gốc từ selfie ở Australia và -ie.", explanationEvidence: "origin of the word … Australia … -ie suffix" },
  36: { explanation: "Gaining popularity trái nghĩa gần: declining (sụt/ giảm).", explanationEvidence: "gaining popularity >< declining" },
  37: { explanation: "Robert Cornelius chụp bức selfie cổ nhất năm 1839.", explanationEvidence: "oldest existing selfie dates back to 1839 … Robert Cornelius" },
  38: { explanation: "Áp lực phải có ảnh đẹp khi sống online ≈ nhu cầu chia sẻ ảnh chất lượng tốt.", explanationEvidence: "pressure to present good quality images" },
  39: { explanation: "Suy luận: mọi lứa tuổi đều selfie (đoạn mở nêu astronauts, Pope…).", explanationEvidence: "social media users of all ages take selfies" },
  40: { explanation: "Toàn bài: selfie không mới, lịch sử lâu, lan rộng nhờ mạng xã hội.", explanationEvidence: "long history from 1839 … global trend … motivations" },
};
