/** Learner-facing explanations — thptqg-simulation-test-6 (Mock 06) */
export const explanations = {
  1: { explanation: "The same enthusiasm for adventure — cần danh từ: enthusiasm (niềm đam mê).", explanationEvidence: "share the same enthusiasm for adventure" },
  2: { explanation: "Wonder about: băn khoăn về điều gì; collocation quen với tình huống chọn bạn đồng hành.", explanationEvidence: "If you often wonder about your travel companions" },
  3: { explanation: "Trật tự: new travel platform (nền tảng du lịch mới).", explanationEvidence: "TravelMate, a new travel platform" },
  4: { explanation: "Others having similar tastes: others + V-ing mệnh đề rút gọn (người có cùng sở thích).", explanationEvidence: "matched with others having similar tastes" },
  5: { explanation: "Make friends: kết bạn — collocation cố định.", explanationEvidence: "looking to make new friends" },
  6: { explanation: "Want to have a relaxing getaway: to have + danh từ sau want to.", explanationEvidence: "want to have a relaxing getaway" },
  7: { explanation: "Some insights: một vài góc nhìn/thống kê hữu ích (mở đoạn brochure).", explanationEvidence: "Here are some insights to help you" },
  8: { explanation: "Devastates aquatic ecosystems: phá hủy hệ sinh thái dưới nước (ngữ cảnh rác nhựa).", explanationEvidence: "discarded plastic … devastates aquatic ecosystems" },
  9: { explanation: "Opt for reusable cutlery: chọn dùng đồ ăn có thể tái sử dụng.", explanationEvidence: "opt for reusable cutlery and plates" },
  10: { explanation: "Instead of discarding: thay vì vứt bỏ — trước khi ném đồ, hãy tái sử dụng.", explanationEvidence: "instead of discarding them" },
  11: { explanation: "Seek brands: tìm kiếm/chọn thương hiệu (động từ phù hợp mua sắm xanh).", explanationEvidence: "When shopping, seek brands that use sustainable materials" },
  12: { explanation: "Manage waste: quản lý phân loại rác; collocation với recycling.", explanationEvidence: "manage waste properly by separating recyclables" },
  13: { explanation: "Hội thoại: Peter hỏi giảm ô nhiễm → Jim gợi ý xe đạp → Peter tán thành.", explanationEvidence: "c → a → b" },
  14: { explanation: "Trao đổi về mạng xã hội: e mở → c Susan → b đồng ý → d hỏi vì sao → a giải thích.", explanationEvidence: "e-c-b-d-a" },
  15: { explanation: "Thư cảm ơn hội chợ: mở b (Dear) → e tình hình hiện tại → a nhớ hội chợ → c cảm ơn → d ấn tượng món ăn.", explanationEvidence: "b-e-a-c-d" },
  16: { explanation: "Báo cáo sự kiện: b mở quan điểm → d tổ chức → c gian hàng → a tham dự → e góp ý.", explanationEvidence: "b-d-a-c-e" },
  17: { explanation: "Theo đáp án c-d-e-a-b: mở bằng ý ‘another benefit’ (c), tiếp nối định nghĩa (d), rồi ‘first of all’ nghề nghiệp (e), phần đời sống xã hội (a), kết luận tổng (b).", explanationEvidence: "order c-d-e-a-b per mock key" },
  18: { explanation: "Cristiano Ronaldo has made a significant impact — câu đầy đủ chủ vị, thì hiện tại hoàn thành phù hợp sự nghiệp.", explanationEvidence: "Ronaldo has made a significant impact on the sport" },
  19: { explanation: "Mệnh đề quan hệ which bổ nghĩa cho 'speed and powerful shots': which made him a formidable opponent.", explanationEvidence: "speed and powerful shots, which made him a formidable opponent" },
  20: { explanation: "Ý chính: tinh thần và kỷ luật của Ronaldo truyền cảm hứng cho vận động viên trẻ.", explanationEvidence: "Ronaldo's relentless drive … inspired many young athletes" },
  21: { explanation: "Câu nhấn mạnh anh luôn thể hiện đẳng cấp hàng đầu (demonstrates why he is considered…).", explanationEvidence: "Ronaldo consistently demonstrates why he is considered one of the best" },
  22: { explanation: "Đoạn từ thiện: nêu rõ anh quyên góp hàng triệu USD cho các tổ chức và hoạt động cứu trợ.", explanationEvidence: "donated millions of dollars to various charities" },
  23: { explanation: "Indigenous (bản địa) trái nghĩa với foreign (ngoại lai).", explanationEvidence: "indigenous traditions >< foreign influences" },
  24: { explanation: "Giá trị Nho giáo nhấn mạnh cộng đồng, hiếu thảo, hòa hợp — không nhấn mạnh individualism.", explanationEvidence: "NOT mentioned: individualism among Confucian values listed" },
  25: { explanation: "Reverence for family ≈ deep respect/admiration for family.", explanationEvidence: "reverence for family and community" },
  26: { explanation: "Câu gạch chân về áo dài: paraphrase gần nhất giữ ‘elegance, modesty, cultural pride’.", explanationEvidence: "Ao dai … fusion of elegance and modesty … cultural identity" },
  27: { explanation: "Their traditions — their trỏ người Việt (Vietnamese people) ở đoạn kết.", explanationEvidence: "the Vietnamese people continue to honor their traditions" },
  28: { explanation: "Đúng theo bài: ẩm thực Việt được ca ngợi toàn cầu (celebrated worldwide).", explanationEvidence: "Vietnamese cuisine is celebrated worldwide" },
  29: { explanation: "While adapting to challenges… — mối quan hệ nhượng bộ (concession) nằm ở đoạn 4.", explanationEvidence: "Paragraph 4: While adapting to the challenges…" },
  30: { explanation: "Đoạn 1: indigenous + external influences — bản sắc chịu ảnh hưởng nội và ngoại.", explanationEvidence: "Paragraph 1: fusion of indigenous traditions and external influences" },
  31: { explanation: "Limited (hạn chế) trái nghĩa: infinite (vô hạn) trong bối cảnh tin tức 24/7.", explanationEvidence: "limited broadcasts >< constant bombardment of news" },
  32: { explanation: "Câu về ‘negativity bias’ giải thích vì sao ta chú ý tin tiêu cực — chèn sau mở đoạn (II).", explanationEvidence: "Insert after sentence introducing human attention to threats" },
  33: { explanation: "Đoạn 3: não bộ tiến hóa để chú ý mối đe dọa — khớp ý ‘negativity bias’.", explanationEvidence: "human brain is hard-wired to seek out … frightening or alarming" },
  34: { explanation: "Them trong ‘make them worry’ trỏ people (viewers/readers).", explanationEvidence: "watching terrible or sad news … make them worry" },
  35: { explanation: "Take a toll on ≈ gây tổn hại, làm suy giảm (ở đây: tổn hại sự lạc quan).", explanationEvidence: "take a toll on our positivity" },
  36: { explanation: "Bài liệt kê stress, anxiety, tiredness, poor sleep, mood — ‘sadness’ không được tách như một hạng mục nghiên cứu riêng theo dạng NOT.", explanationEvidence: "effects mentioned vs. sadness as separate category" },
  37: { explanation: "Đoạn kết: ta có quyền chọn lượng và loại tin tiêu thụ.", explanationEvidence: "we have a choice … how much news … kind of news" },
  38: { explanation: "Paraphrase câu gạch chân đoạn 5: cân nhắc cả số lượng và chất lượng nguồn tin.", explanationEvidence: "mindful of both how much and what kind of news" },
  39: { explanation: "Suy luận: kênh tin 24 giờ làm tăng lượng tin tiếp xúc (so với thời báo giấy).", explanationEvidence: "24-hour news channels … constantly bombarded" },
  40: { explanation: "Tóm lược: được thông tin là tốt, nhưng quá nhiều tin tiêu cực có hại — cần chọn lọc.", explanationEvidence: "staying informed … choice … kind of news … health" },
};
