/** Learner-facing explanations — thptqg-simulation-test-7 (Mock 07) */
export const explanations = {
  1: { explanation: "Trung tâm du khách được thiết kế (designed) — quá khứ phân từ / reduced relative bổ nghĩa tòa nhà.", explanationEvidence: "visitor centre … designed … uses solar panels" },
  2: { explanation: "Khoản trợ cấp nhằm thúc đẩy (promote) lắp đặt pin mái nhà — chọn dạng từ/cấu trúc khớp mạch grants + household installation.", explanationEvidence: "grants … household installation of rooftop panels" },
  3: { explanation: "Green energy option: cụm danh từ đúng thứ tự (lựa chọn năng lượng xanh).", explanationEvidence: "pick the green energy option from their electricity supplier" },
  4: { explanation: "Make a difference: tạo ra thay đổi/ tác động lâu dài đến khí thải.", explanationEvidence: "can make a lasting difference to local emissions" },
  5: { explanation: "Reserved for: dành riêng cho (ngân sách cho nhóm cộng đồng).", explanationEvidence: "funding was reserved for neighbourhood groups" },
  6: { explanation: "Every voluntary act: act (hành động) là danh từ đếm được phù hợp ‘mỗi hành động tự nguyện’.", explanationEvidence: "every voluntary act … signals commitment" },
  7: { explanation: "Helping those in need is rewarding (đáng làm, mang lại niềm vui/ý nghĩa).", explanationEvidence: "Helping those in need is rewarding" },
  8: { explanation: "Thanks to your contributions: nhờ có đóng góp — không dùng Regardless of (bất kể) vì mất nghĩa tích cực.", explanationEvidence: "Thanks to your contributions … communities become closer" },
  9: { explanation: "Give away clothes/food: cho đi, tặng lại đồ cho người cần.", explanationEvidence: "give away clothes, food … to those in need" },
  10: { explanation: "Donate a portion/range of income — chọn cụm khớp đề (thường gặp ‘a portion of income’; đề có thể dùng ‘range’ để chỉ khoảng đóng góp linh hoạt).", explanationEvidence: "donate … of your income to trusted charities" },
  11: { explanation: "Offer assistance that could benefit others: others = người khác (đại từ số nhiều không xác định).", explanationEvidence: "benefit others" },
  12: { explanation: "Events promote awareness: nâng cao nhận thức (collocation với charity events).", explanationEvidence: "charity events that promote awareness" },
  13: { explanation: "Mua điện thoại: nhân viên chào hàng (b) → khách hỏi (d) → tư vấn (b lần 2?) — trình tự b-d-e-c-a theo đáp án.", explanationEvidence: "sales dialogue flow b-d-e-c-a" },
  14: { explanation: "Trình tự a-b-d-e-c: mở xu hướng internet (a) → công nghệ đổi cuộc sống (b) → cân bằng lợi/hại (d) → tiến bộ AI (e) → thách thức (c).", explanationEvidence: "paragraph chain a-b-d-e-c" },
  15: { explanation: "Mua quà: Julia chào và nói nhu cầu (a) → nhân viên chào mừng và liệt kê (c) → Julia chọn nến (b). Trình tự a-c-b.", explanationEvidence: "gift shop dialogue a-c-b" },
  16: { explanation: "Học ngoại ngữ: khó khăn ban đầu (b) → nản (d) → tuy nhiên nền tảng (a) → luyện tập (c) → thành tựu (e). Thứ tự a-d-c-b-e.", explanationEvidence: "language learning a-d-c-b-e" },
  17: { explanation: "Thư giao việc leaflet: b (nội dung cần) → c (thuyết phục trẻ) → e (giao thêm việc) → d (cách viết vui) → a (cảm ơn).", explanationEvidence: "b-c-e-d-a" },
  18: { explanation: "Varied methods … that have been introduced by technology recently — mệnh đề quan hệ đầy đủ.", explanationEvidence: "methods that have been introduced by technology recently" },
  19: { explanation: "Personalized learning trend — câu mô tả AI điều chỉnh nội dung (chọn đúng dạng điền trong đề).", explanationEvidence: "personalized learning … AI tailors content" },
  20: { explanation: "Gamification: nhiều app dùng điểm và bảng xếp hạng để khuyến khích học mỗi ngày.", explanationEvidence: "Many learning apps now use point systems and leaderboards" },
  21: { explanation: "Collaborative learning: học sinh nhiều nước dùng Zoom/Docs rồi chia sẻ ý tưởng — câu chủ động, rõ chủ thể.", explanationEvidence: "Students from different countries can now use platforms … allowing them to share" },
  22: { explanation: "Đoạn kết: learners can now meet the demands… hoặc câu tương đương trong đề để khép ‘Making use of these approaches’.", explanationEvidence: "closing sentence on modern learners" },
  23: { explanation: "Bài không nhắc ủ phân composting như một thói quen đã liệt kê rõ.", explanationEvidence: "composting not listed among explicit practices" },
  24: { explanation: "Vital (thiết yếu) trái nghĩa: inessential (không thiết yếu).", explanationEvidence: "vital >< inessential" },
  25: { explanation: "When green living habits are adopted, they — they = green living habits.", explanationEvidence: "When green living habits are adopted, they can lead to profound changes" },
  26: { explanation: "Empowering individuals ≈ enabling individuals (trao quyền, tạo điều kiện).", explanationEvidence: "empowering individuals to make informed choices" },
  27: { explanation: "Câu gạch chân: chọn sản phẩm thân thiện môi trường ủng hộ doanh nghiệp có trách nhiệm.", explanationEvidence: "Choosing eco-friendly products supports responsible businesses" },
  28: { explanation: "Túi tái sử dụng giảm rác nhựa — đúng theo đoạn 2.", explanationEvidence: "reusable bags … reduce plastic waste" },
  29: { explanation: "Consequently trong đoạn 3 thể hiện quan hệ nhân–quả (giảm phát thải → không khí sạch hơn).", explanationEvidence: "Consequently, this contributes to cleaner air" },
  30: { explanation: "Workshops, social media campaigns nêu ở đoạn 4 — cách ‘dạy’ sống xanh.", explanationEvidence: "Paragraph 4: workshops and social media campaigns" },
  31: { explanation: "AR/VR làm tương tác từ xa gần như gặp trực tiếp — đúng đoạn CES.", explanationEvidence: "AR glasses … remote interactions feel as natural as face-to-face" },
  32: { explanation: "Woven into every fabric of daily lives ≈ integrated throughout everyday routines.", explanationEvidence: "AI woven into every fabric of our daily lives" },
  33: { explanation: "Conscious (có ý thức) trái nghĩa: oblivious (vô tình, không hay biết).", explanationEvidence: "conscious >< oblivious" },
  34: { explanation: "Câu ví dụ thiết bị phân hủy sinh học chèn vào phần xu hướng bền vững (III) trong đoạn có (I)–(IV).", explanationEvidence: "eco-friendly gadgets … biodegradable wearables" },
  35: { explanation: "Đoạn 3 IoT và nhà thông minh: tóm tắt gần nhất là IoT trực quan, kết nối hơn.", explanationEvidence: "IoT … smart homes … interconnected" },
  36: { explanation: "EXCEPT: bài chỉ suy đoán/educated speculation — không hứa hẹn ‘confirmed updates’ sản phẩm cụ thể.", explanationEvidence: "educated speculations vs confirmed product updates" },
  37: { explanation: "Tủ lạnh gợi ý công thức để giảm lãng phí thực phẩm.", explanationEvidence: "refrigerators … suggest recipes to reduce food waste" },
  38: { explanation: "Câu gạch chân đoạn y tế–công nghệ: công nghệ giúp sống khỏe và chủ động hơn với sức khỏe.", explanationEvidence: "integration of tech and wellness … healthier, more informed lives" },
  39: { explanation: "Giọng văn đầy từ ‘thrilling’, ‘magic’, ‘marvel’ — lạc quan về tiềm năng công nghệ.", explanationEvidence: "optimistic tone toward CES innovations" },
  40: { explanation: "Tóm lược: các ý tưởng mang tính suy đoán có cơ sở (educated speculations), không phải báo cáo đã xác nhận.", explanationEvidence: "educated speculations … unexpected innovations" },
};
